<?php
declare(strict_types=1);

/*
 * Router for PHP's built-in web server.
 *
 * Usage:
 *   php -S 127.0.0.1:8000 router.php
 *
 * This mirrors the Apache rewrite rules generated by FBP:
 *   /class*function        -> /fbp/app.php?class=class&function=function
 *   /class*function&a=b    -> /fbp/app.php?class=class&function=function&a=b
 *   /css/...               -> /fbp/css/...
 *   /js/...                -> /fbp/js/...
 *   /images/...            -> /classes/app/images/...
 */

$fbp_router_root = __DIR__;
$fbp_router_base_path = fbp_router_base_path();
$fbp_router_request_uri = (string) ($_SERVER["REQUEST_URI"] ?? "/");
$fbp_router_paths = fbp_router_request_paths($fbp_router_request_uri, $fbp_router_base_path);

if ($fbp_router_paths === null) {
	fbp_router_status(400, "Bad Request");
	return true;
}

$fbp_router_path = $fbp_router_paths["path"];
$fbp_router_raw_path = $fbp_router_paths["raw_path"];
$fbp_router_original_query = fbp_router_request_query($fbp_router_request_uri);

if (fbp_router_is_dotfile_path($fbp_router_path)) {
	fbp_router_status(403, "Forbidden");
	return true;
}

if (fbp_router_is_protected_path($fbp_router_path)) {
	fbp_router_status(403, "Forbidden");
	return true;
}

if ($fbp_router_path === "/" || $fbp_router_path === "") {
	$root_class = fbp_router_env("FBP_ROOT_CLASS", "login");
	$root_function = fbp_router_env("FBP_ROOT_FUNCTION", "page");
	fbp_router_run_php(
		$fbp_router_root,
		"/fbp/app.php",
		fbp_router_build_query([
			"class" => $root_class,
			"function" => $root_function,
		], $fbp_router_original_query),
		$fbp_router_base_path,
		[
			"class" => $root_class,
			"function" => $root_function,
		]
	);
	return true;
}

if (preg_match("#^/fw4(?:/(.*))?$#i", $fbp_router_path, $matches)) {
	$target = fbp_router_with_base($fbp_router_base_path, "/fbp/" . ($matches[1] ?? ""));
	if ($fbp_router_original_query !== "") {
		$target .= "?" . $fbp_router_original_query;
	}
	header("Location: " . $target, true, 301);
	return true;
}

if ($fbp_router_path === "/fbp") {
	fbp_router_run_php($fbp_router_root, "/fbp/app.php", $fbp_router_original_query, $fbp_router_base_path);
	return true;
}

if (preg_match("#^/classes/app/images/.+#i", $fbp_router_path)) {
	fbp_router_send_project_file($fbp_router_root, $fbp_router_path);
	return true;
}

if (preg_match("#^/(?:fbp/)?images/(.+)$#i", $fbp_router_path, $matches)) {
	fbp_router_send_project_file($fbp_router_root, "/classes/app/images/" . $matches[1]);
	return true;
}

if ($fbp_router_path === "/robots.txt") {
	fbp_router_send_project_file($fbp_router_root, "/robots.txt");
	return true;
}

if (!preg_match("#^/fbp/#i", $fbp_router_path) && strpos($fbp_router_raw_path, "*") !== false) {
	[$class, $function, $inline_query] = fbp_router_parse_star_route($fbp_router_raw_path);
	$query = fbp_router_build_query(
		[
			"class" => $class,
			"function" => $function,
		],
		$inline_query,
		$fbp_router_original_query
	);
	fbp_router_run_php($fbp_router_root, "/fbp/app.php", $query, $fbp_router_base_path, [
		"class" => $class,
		"function" => $function,
	]);
	return true;
}

if (preg_match("#^/app/(.*)$#i", $fbp_router_path, $matches)) {
	fbp_router_dispatch_fbp_path($fbp_router_root, "/" . $matches[1], $fbp_router_original_query, $fbp_router_base_path);
	return true;
}

if (!preg_match("#^/fbp/#i", $fbp_router_path) && !preg_match("#\.[^/]+$#", $fbp_router_path)) {
	$default_class = fbp_router_env("FBP_DEFAULT_CLASS", "");
	$function = ltrim($fbp_router_path, "/");
	$query = fbp_router_build_query(
		[
			"class" => $default_class,
			"function" => $function,
		],
		$fbp_router_original_query
	);
	fbp_router_run_php($fbp_router_root, "/fbp/app.php", $query, $fbp_router_base_path, [
		"class" => $default_class,
		"function" => $function,
	]);
	return true;
}

if (!preg_match("#^/fbp/#i", $fbp_router_path)) {
	fbp_router_dispatch_fbp_path($fbp_router_root, $fbp_router_path, $fbp_router_original_query, $fbp_router_base_path);
	return true;
}

fbp_router_dispatch_fbp_path($fbp_router_root, substr($fbp_router_path, 4), $fbp_router_original_query, $fbp_router_base_path);
return true;

function fbp_router_env(string $name, string $default): string {
	$value = getenv($name);
	if (!is_string($value) || $value === "") {
		return $default;
	}
	return $value;
}

function fbp_router_base_path(): string {
	$base = fbp_router_env("FBP_BASE_PATH", "");
	$base = trim($base);
	if ($base === "" || $base === "/") {
		return "";
	}
	return "/" . trim($base, "/");
}

function fbp_router_with_base(string $base_path, string $path): string {
	$path = "/" . ltrim($path, "/");
	return ($base_path === "") ? $path : $base_path . $path;
}

function fbp_router_request_query(string $request_uri): string {
	$query = parse_url($request_uri, PHP_URL_QUERY);
	return is_string($query) ? $query : "";
}

function fbp_router_request_paths(string $request_uri, string $base_path): ?array {
	$raw_path = parse_url($request_uri, PHP_URL_PATH);
	if (!is_string($raw_path) || $raw_path === "") {
		$raw_path = "/";
	}
	$raw_path = "/" . ltrim($raw_path, "/");
	$raw_path = preg_replace("#/+#", "/", $raw_path);
	if (!is_string($raw_path)) {
		return null;
	}

	if ($base_path !== "" && ($raw_path === $base_path || strpos($raw_path, $base_path . "/") === 0)) {
		$raw_path = substr($raw_path, strlen($base_path));
		if ($raw_path === "") {
			$raw_path = "/";
		}
	}

	$raw_segments = explode("/", trim($raw_path, "/"));
	$normalized_raw_segments = [];
	$decoded_segments = [];

	foreach ($raw_segments as $segment) {
		if ($segment === "" || $segment === ".") {
			continue;
		}
		$decoded = rawurldecode($segment);
		if (
			$decoded === "" ||
			$decoded === "." ||
			$decoded === ".." ||
			strpos($decoded, "\0") !== false ||
			strpos($decoded, "/") !== false ||
			strpos($decoded, "\\") !== false
		) {
			return null;
		}
		$normalized_raw_segments[] = $segment;
		$decoded_segments[] = $decoded;
	}

	return [
		"raw_path" => "/" . implode("/", $normalized_raw_segments),
		"path" => "/" . implode("/", $decoded_segments),
	];
}

function fbp_router_is_dotfile_path(string $path): bool {
	foreach (explode("/", trim($path, "/")) as $segment) {
		if ($segment !== "" && strpos($segment, ".") === 0) {
			return true;
		}
	}
	return false;
}

function fbp_router_is_protected_path(string $path): bool {
	$lower = strtolower($path);
	if ($lower === "/fbp/cli.php") {
		return true;
	}
	foreach (["app", "interface", "lib", "lib_ext", "templates", "docs"] as $dir) {
		if ($lower === "/fbp/" . $dir || strpos($lower, "/fbp/" . $dir . "/") === 0) {
			return true;
		}
	}
	if (strpos($lower, "/classes/") === 0 && strpos($lower, "/classes/app/images/") !== 0) {
		return true;
	}
	return false;
}

function fbp_router_parse_star_route(string $raw_path): array {
	$route = ltrim($raw_path, "/");
	[$raw_class, $raw_rest] = array_pad(explode("*", $route, 2), 2, "");
	$raw_function = $raw_rest;
	$inline_query = "";

	$amp_pos = strpos($raw_rest, "&");
	if ($amp_pos !== false) {
		$raw_function = substr($raw_rest, 0, $amp_pos);
		$inline_query = substr($raw_rest, $amp_pos + 1);
	}

	return [
		rawurldecode($raw_class),
		rawurldecode($raw_function),
		$inline_query,
	];
}

function fbp_router_build_query(array $params, string ...$extra_queries): string {
	$query = http_build_query($params, "", "&", PHP_QUERY_RFC3986);
	foreach ($extra_queries as $extra_query) {
		$extra_query = ltrim($extra_query, "?&");
		if ($extra_query === "") {
			continue;
		}
		$query .= ($query === "" ? "" : "&") . $extra_query;
	}
	return $query;
}

function fbp_router_dispatch_fbp_path(string $root, string $path, string $query, string $base_path): void {
	$fbp_path = "/fbp/" . ltrim($path, "/");
	if (fbp_router_is_dotfile_path($fbp_path) || fbp_router_is_protected_path($fbp_path)) {
		fbp_router_status(403, "Forbidden");
		return;
	}

	$absolute = fbp_router_absolute_path($root, $fbp_path);
	if ($absolute === null || !is_file($absolute)) {
		fbp_router_status(404, "Not Found");
		return;
	}

	if (preg_match("#^/fbp/[^/]+\.php$#i", $fbp_path)) {
		fbp_router_run_php($root, $fbp_path, $query, $base_path);
		return;
	}

	if (fbp_router_is_public_static_path($fbp_path)) {
		fbp_router_send_project_file($root, $fbp_path);
		return;
	}

	fbp_router_status(404, "Not Found");
}

function fbp_router_is_public_static_path(string $path): bool {
	$lower = strtolower($path);
	return (
		strpos($lower, "/fbp/css/") === 0 ||
		strpos($lower, "/fbp/js/") === 0 ||
		strpos($lower, "/classes/app/images/") === 0 ||
		$lower === "/robots.txt"
	);
}

function fbp_router_run_php(
	string $root,
	string $script_path,
	string $query,
	string $base_path,
	array $force_get = []
): void {
	$absolute = fbp_router_absolute_path($root, $script_path);
	if ($absolute === null || !is_file($absolute)) {
		fbp_router_status(404, "Not Found");
		return;
	}

	fbp_router_set_query($query, $force_get);

	$script_name = fbp_router_with_base($base_path, $script_path);
	$_SERVER["SCRIPT_NAME"] = $script_name;
	$_SERVER["PHP_SELF"] = $script_name;
	$_SERVER["SCRIPT_FILENAME"] = $absolute;
	$_SERVER["DOCUMENT_ROOT"] = $root;

	chdir(dirname($absolute));
	require $absolute;
}

function fbp_router_set_query(string $query, array $force_get = []): void {
	$_SERVER["QUERY_STRING"] = $query;
	$get = [];
	if ($query !== "") {
		parse_str($query, $get);
	}
	foreach ($force_get as $key => $value) {
		$get[$key] = $value;
	}
	$_GET = $get;
	$_REQUEST = array_merge($_COOKIE, $_POST, $_GET);
}

function fbp_router_send_project_file(string $root, string $path): void {
	if (fbp_router_is_dotfile_path($path) || fbp_router_is_protected_path($path)) {
		fbp_router_status(403, "Forbidden");
		return;
	}
	if (preg_match("#\.ph(?:p[0-9]?|ar|tml)$#i", $path)) {
		fbp_router_status(403, "Forbidden");
		return;
	}

	$absolute = fbp_router_absolute_path($root, $path);
	if ($absolute === null || !is_file($absolute)) {
		fbp_router_status(404, "Not Found");
		return;
	}
	if (!fbp_router_is_public_static_path($path)) {
		fbp_router_status(404, "Not Found");
		return;
	}

	$mime = fbp_router_mime_type($absolute);
	header("Content-Type: " . $mime);
	header("X-Content-Type-Options: nosniff");
	$size = filesize($absolute);
	if ($size !== false) {
		header("Content-Length: " . $size);
	}
	if (($_SERVER["REQUEST_METHOD"] ?? "GET") === "HEAD") {
		return;
	}
	readfile($absolute);
}

function fbp_router_absolute_path(string $root, string $path): ?string {
	$root_real = realpath($root);
	if ($root_real === false) {
		return null;
	}
	$absolute = $root_real . "/" . ltrim($path, "/");
	$real = realpath($absolute);
	if ($real === false || strpos($real, $root_real . DIRECTORY_SEPARATOR) !== 0) {
		return null;
	}
	return $real;
}

function fbp_router_mime_type(string $absolute): string {
	$ext = strtolower(pathinfo($absolute, PATHINFO_EXTENSION));
	$map = [
		"css" => "text/css; charset=UTF-8",
		"js" => "application/javascript; charset=UTF-8",
		"json" => "application/json; charset=UTF-8",
		"txt" => "text/plain; charset=UTF-8",
		"html" => "text/html; charset=UTF-8",
		"png" => "image/png",
		"gif" => "image/gif",
		"jpg" => "image/jpeg",
		"jpeg" => "image/jpeg",
		"svg" => "image/svg+xml",
		"ico" => "image/x-icon",
		"webp" => "image/webp",
		"woff" => "font/woff",
		"woff2" => "font/woff2",
		"ttf" => "font/ttf",
		"eot" => "application/vnd.ms-fontobject",
	];
	if (isset($map[$ext])) {
		return $map[$ext];
	}
	if (function_exists("finfo_open")) {
		$finfo = finfo_open(FILEINFO_MIME_TYPE);
		if ($finfo !== false) {
			$mime = finfo_file($finfo, $absolute);
			finfo_close($finfo);
			if (is_string($mime) && $mime !== "") {
				return $mime;
			}
		}
	}
	return "application/octet-stream";
}

function fbp_router_status(int $status, string $message): void {
	http_response_code($status);
	header("Content-Type: text/plain; charset=UTF-8");
	if (($_SERVER["REQUEST_METHOD"] ?? "GET") !== "HEAD") {
		echo $message;
	}
}
