<?php
class Controller { function t($key, $params=[]) { return $key; } function cron_set() {} function get_setting() { return ['project_release_code'=>'app-target']; } }
require_once __DIR__ . '/../fbp/app/release/ReleaseManager.php';
function check($ok, $message) { if (!$ok) throw new RuntimeException($message); }
function removeTree($path) { if (!is_dir($path)) return; foreach (new FilesystemIterator($path) as $f) { if ($f->isDir()) removeTree($f->getPathname()); else unlink($f->getPathname()); } rmdir($path); }
$base = __DIR__ . '/tmp-release-db-' . bin2hex(random_bytes(5));
try {
	foreach (['legacy', 'off', 'on', 'off_included'] as $mode) {
		$source = $base . '/' . $mode . '/source'; $target = $base . '/' . $mode . '/target';
		foreach ([$source, $target] as $path) { mkdir($path . '/classes/app', 0777, true); mkdir($path . '/classes/data/db', 0777, true); mkdir($path . '/classes/data/db_additionals', 0777, true); mkdir($path . '/classes/data/constant_array', 0777, true); mkdir($path . '/classes/data/_common/fmt', 0777, true); file_put_contents($path . '/classes/app/current.php', 'current'); }
		file_put_contents($source . '/classes/data/db/db.dat', 'SOURCE_DB'); file_put_contents($source . '/classes/data/db_additionals/additionals.dat', 'SOURCE_ADDITIONALS'); file_put_contents($source . '/classes/data/constant_array/constant_array.dat', 'SOURCE_CONSTANTS'); file_put_contents($source . '/classes/data/constant_array/values.dat', 'SOURCE_VALUES'); file_put_contents($source . '/classes/data/_common/fmt/notes.fmt', 'SOURCE_FMT');
		file_put_contents($target . '/classes/data/db/db.dat', 'TARGET_DB'); file_put_contents($target . '/classes/data/db/local.dat', 'LOCAL_DB'); file_put_contents($target . '/classes/data/db_additionals/additionals.dat', 'TARGET_ADDITIONALS'); file_put_contents($target . '/classes/data/constant_array/constant_array.dat', 'TARGET_CONSTANTS'); file_put_contents($target . '/classes/data/constant_array/values.dat', 'TARGET_VALUES'); file_put_contents($target . '/classes/data/_common/fmt/notes.fmt', 'TARGET_FMT');
		$info = ['project_release_code'=>'app-target', 'type'=>'release']; if ($mode !== 'legacy') $info['deploy_db_definitions'] = !str_starts_with($mode, 'off');
		$zipPath = $base . '/' . $mode . '/payload.zip'; (new ReleaseManager($source, $zipPath))->create_release_zip_from_info($info);
		$zip = new ZipArchive(); $zip->open($zipPath); foreach (['data/db/db.dat', 'data/db_additionals/additionals.dat', 'data/constant_array/constant_array.dat', 'data/constant_array/values.dat', 'data/_common/fmt/notes.fmt'] as $entry) check(($zip->locateName($entry) !== false) === !str_starts_with($mode, 'off'), 'sender definition policy: ' . $entry); if ($mode === 'off_included') { foreach (['data/db/db.dat', 'data/db_additionals/additionals.dat', 'data/constant_array/constant_array.dat', 'data/constant_array/values.dat', 'data/_common/fmt/notes.fmt'] as $entry) $zip->addFromString($entry, 'MUST_NOT_DEPLOY'); } if ($mode === 'legacy') $zip->addFromString('info.json', json_encode(['project_release_code'=>'app-target','type'=>'release'])); $zip->close();
		$receiver = new ReleaseManager($target); $receiver->validate_release_zip(new Controller(), $zipPath); (new ReleaseManager($target))->apply_release_zip(new Controller(), $zipPath);
		$off = str_starts_with($mode, 'off'); check(file_get_contents($target . '/classes/data/db/db.dat') === ($off ? 'TARGET_DB' : 'SOURCE_DB'), 'DB changed incorrectly'); check(file_exists($target . '/classes/data/db/local.dat') === $off, 'DB deletion policy'); check(file_get_contents($target . '/classes/data/db_additionals/additionals.dat') === ($off ? 'TARGET_ADDITIONALS' : 'SOURCE_ADDITIONALS'), 'additionals changed incorrectly'); check(file_get_contents($target . '/classes/data/constant_array/constant_array.dat') === ($off ? 'TARGET_CONSTANTS' : 'SOURCE_CONSTANTS'), 'constants changed incorrectly'); check(file_get_contents($target . '/classes/data/constant_array/values.dat') === ($off ? 'TARGET_VALUES' : 'SOURCE_VALUES'), 'constant values changed incorrectly'); check(file_get_contents($target . '/classes/data/_common/fmt/notes.fmt') === ($off ? 'TARGET_FMT' : 'SOURCE_FMT'), 'fmt changed incorrectly');
	}
	mkdir($base . '/invalid/classes', 0777, true);
	try { (new ReleaseManager($base . '/invalid', $base . '/bad.zip'))->create_release_zip_from_info(['deploy_db_definitions'=>'invalid']); throw new LogicException('accepted invalid DB policy'); } catch (RuntimeException $expected) {}
	echo "Release DB definition policy: sender, receiver, definition data and fmt preservation passed\n";
} finally { removeTree($base); }
